### ISSUE TITLE
[BUG] Release 0.9.3 doesn't do anything

### ISSUE THREAD

**Issue by gradius-v** [Neuroquila-n8fall/JunkersControl#22]
I flashed the files to an ESP32 board, but its just dead afterward and doesn't do anything. The old version from a year ago works.

**Comment by Neuroquila-n8fall** [comment]
After flashing the "firmware" it should output on the serial console that the configuration is missing. After that, flash the "filesystem". 
If this doesn't work you might have to erase the whole flash using esptools or platformio. This happened once in my experience and has something to do with how the filesystem is aligned during the first flash.

If you push the "boot" button within 5 seconds of booting it should open up an Wifi AP. Is this the case?

**Comment by gradius-v** [comment]
I should not try to report bugs in the middle the night.. :)
Just got around to testing some more and it turns out the flash memory of the ESP32 is bad, tried another one and it works fine.
Sorry for the sloppy bug report. Can probably be deleted.

**Comment by Neuroquila-n8fall** [comment]
Alright thank you for reporting back :)
