### ISSUE TITLE
Outside temp [BUG]

### ISSUE THREAD

**Issue by auwe** [Neuroquila-n8fall/JunkersControl#25]
**Describe the bug**
Die Aussentemperatur wird bei mir unter 0 Grad nicht korrekt berechnet. 

Ich denke, dass die Variable int rawTemp in der Datei can_processor.cpp nicht unsigned sein darf.
<img width="172" alt="image" src="https://user-images.githubusercontent.com/37331943/208727638-a7d66db8-1e01-4137-bb83-2dc2b9a61cb5.png">

und beim Daten auslesen musste ich auch noch was anpassen.
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/37331943/208728099-ad21ab1f-cee3-4617-bb5d-718bbeeb7839.png">

**Comment by Neuroquila-n8fall** [comment]
Absolut korrekt. Danke!

**Comment by Neuroquila-n8fall** [comment]
OK also du betrachtest bei deiner Variante alle Bytes in der Nachricht. Welches Heizungsmodell ist das und wie sehen die Rohdaten aus? Nicht, dass wir in ein generelles Problem hier rein rennen...

**Comment by auwe** [comment]
Mir ist gerade noch aufgefallen, dass das sizeof() ein blöde Idee war, da das Array immer 8 Byte große ist.
Und die Variable rawTemp muss vom Datentyp short sein, da sonst die negativen Zahlen nicht richtig interpretiert werden. 
![image](https://user-images.githubusercontent.com/37331943/208975849-97c080e8-f095-40aa-bf34-8fbbb5b3148f.png)
Hab es zwar noch nicht mit negativen Werten vom Sensor getestet, da wir ja keine Minusgrade mehr haben, aber mit Fakedaten sieht es mal gut aus.
Sorry, dass ich es nicht gleich richtig getestet habe. :(

**Comment by auwe** [comment]
.... und deine Variante mit 
`short rawTemp1 = (arr[0] << 8) + arr[1];`
klaptt auch, wenn der Datentyp passt. Von `unsigned int` auf `short` umgestellt und alles gut. 
So einfach wäre es gegangen, wenn ich mir das mit dem 2er-Komplement davor nochmals angesehen hätte.
