### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by marty71bk** [Neuroquila-n8fall/JunkersControl#47]
Hi,
Very basic question due to lack of experience with unix environment. Then sorry  for bothering with such kind of question in advance.
Setup:
Raspberry PI5 with 2ch- CAN HAT module https://www.waveshare.com/wiki/2-CH_CAN_HAT
Running HAOS on PI5 with using add-ons SSH for accessing terminal and MQTT broker to leverage communication between CAN module and Home Assistant
Currently dealing with enabling see network interface can0 and can1 in linux (ip link does not see them)
To the topic (installation):
How can I install repo on Raspberry with HAOS and complete the instalation? 
Is there a kind of step by step guidance for amateurs?
Thanks.

**Comment by Neuroquila-n8fall** [comment]
Sorry for the late reply. I don't know how this could work on a PI directly as this project is entirely made for ESP SOCs. If you're experienced enough you could use something like python to interact with the CAN messages directly over the PIs interface.

Short answer: not directly possible with this project but may be adapted to run directly on PI.
