### ISSUE TITLE
lot of errors "multiple definition of `mqttPASSWORD`" etc. from arduino_secrets.h

### ISSUE THREAD

**Issue by rejoe2** [Neuroquila-n8fall/JunkersControl#6]
Hi there,

this seems to be a great project! Unfortunately, platformIO refuses to compile the code throwing a lot of variants of the above mentionned messages. Compiling is ending up in "collect2: error: ld returned 1 exit status".

Environment: Kubuntu 20.04, atom, PlatformIO Core version 6.1.3.

As prerequisites, 
- in platform.ini file lib_deps for eZtime had to be changed to ropg/ezTime@^0.8.3, and
- a single file arduino_secrets.h in folder "include" has been added containing my personal credentials as described in the respective .template file. The respective .cpp is not added (any longer).

Compile run seems to start fine, but will end up with the mentionned error.

Tried also with the cpp-credential file, changed #includes for the credentials from <> to "" syntax etc., added both under the "lib"-path, no luck with any of that either...

Most likely I missed something essential?
For the deeper understandig: I managed to get some other smaller projects compiled with pio@atom some time ago, but I'm far from beeing experienced user in these tools.

So any tipp for getting that done is highly appreciated.

EDIT: OK, after disabling all referencies to the secrets-file and filling in the credentials directly into the files mqtt.cpp and wifi_config.cpp, there's finaly a firmware ready to flash...

**Comment by rejoe2** [comment]
Will come back in case of further issues...

**Comment by Neuroquila-n8fall** [comment]
Thanks for letting know.
I will update my tooling and check if i can reproduce the issues.

**Comment by rejoe2** [comment]
Thanks a lot for your answer.
The changed referency for ezTime had been already mentionned in Mikrocontroler-forum as well.
Wrt. to the wifi settings, I had some older libs laying around in my "Arduino" folder causing trouble in another project as well. I'll double-check that as well.

Besides that: Yesterday evening my Junkers got switched off by MQTT command, BIG THANKS - a long time dream came true!
